using JuMP
using Random
using Distributions

"""
    OperatingRoomMasterScheduleProblem <: ProblemGenerator

Tactical cyclic master-surgical-schedule (MSS) design.  Compatible
specialty/room/day blocks are assigned subject to minimum/maximum block quotas,
daily concentration limits, and room exclusivity.  Separate expected ICU and
post-ICU ward profiles are convolved cyclically with the block plan and capped;
peak variables level both downstream resources.

Only compatible assignment variables are created.  Feasible instances retain
the complete planted block plan; infeasible instances carry an LP-level quota
certificate requiring more blocks for one service than all its compatible
room-days can provide.
"""
struct OperatingRoomMasterScheduleProblem <: ProblemGenerator
    n_specialties::Int
    n_rooms::Int
    n_days::Int
    specialty_names::Vector{Symbol}
    target_blocks::Vector{Int}
    min_blocks::Vector{Int}
    max_blocks::Vector{Int}
    max_daily_rooms::Vector{Int}
    room_specialty_compatible::BitMatrix
    admissible_blocks::Vector{Tuple{Int, Int, Int}}
    preference_cost::Vector{Float64}
    room_open_cost::Matrix{Float64}
    ward_profile::Matrix{Float64}
    icu_profile::Matrix{Float64}
    ward_capacity::Vector{Float64}
    icu_capacity::Vector{Float64}
    under_penalty::Vector{Float64}
    over_penalty::Vector{Float64}
    peak_ward_weight::Float64
    peak_icu_weight::Float64
    feasible_witness::Union{Nothing, Array{Int, 3}}
    infeasible_specialty::Union{Nothing, Int}
    feasibility_status::FeasibilityStatus
end

function _mss_dimensions(target::Int)
    best = nothing
    best_gap = typemax(Int)
    max_rooms = max(8, ceil(Int, sqrt(target / 3)))
    for d in (5, 10), r in 2:max_rooms, s in 2:min(11, r * d)
        fixed = r * d + 2s + 2d + 2
        pairs = clamp(round(Int, (target - fixed) / d), s, s * r)
        total = pairs * d + fixed
        gap = abs(total - target)
        if gap < best_gap
            best_gap = gap
            best = (s=s, r=r, d=d, pairs=pairs)
        end
    end
    return best
end

# Survival probability for a discrete-uniform LOS. `minimum_los=1` matches the
# post-ICU path in `_orsched_waiting_list`, where a sampled zero is raised to
# one ward day after critical-care discharge.
function _mss_uniform_los_survival(los::Tuple{Int, Int}, age::Int; minimum_los::Int=0)
    age < 0 && return 0.0
    lo, hi = los
    return count(length_of_stay -> max(minimum_los, length_of_stay) > age, lo:hi) / (hi - lo + 1)
end

# Expected occupancy generated by one block of a single specialty.  This uses
# the same discrete patient path as the weekly generator: ICU LOS is uniform
# on 1:2, then the patient enters the ward; non-ICU admissions enter the ward
# directly. Contributions beyond the cycle are folded back by phase, which is
# the exact occupancy profile for a repeating MSS.
function _mss_profile_components(profile, n_days::Int)
    cases_per_block = 480.0 / (profile.aggregate_mean + 25.0)
    direct_ward = zeros(Float64, n_days)
    post_icu_ward = zeros(Float64, n_days)
    icu = zeros(Float64, n_days)
    max_lag = max(2, profile.ward_los[2] + 1)

    for lag in 0:max_lag
        phase = mod(lag, n_days) + 1

        # Half the ICU cohort has LOS 1 and half LOS 2. At lag 1, the former
        # half is in the ward while the latter half remains in ICU.
        icu_survival = if lag == 0
            1.0
        elseif lag == 1
            0.5
        else
            0.0
        end
        icu[phase] += cases_per_block * profile.icu * icu_survival

        direct_survival = _mss_uniform_los_survival(profile.ward_los, lag)
        direct_ward[phase] +=
            cases_per_block * (1 - profile.icu) * (1 - profile.day_case) * direct_survival

        if lag >= 1
            # Discharge after one ICU day (probability 1/2).
            post_icu_ward[phase] +=
                cases_per_block *
                profile.icu *
                0.5 *
                _mss_uniform_los_survival(profile.ward_los, lag - 1; minimum_los=1)
        end
        if lag >= 2
            # Discharge after two ICU days (probability 1/2).
            post_icu_ward[phase] +=
                cases_per_block *
                profile.icu *
                0.5 *
                _mss_uniform_los_survival(profile.ward_los, lag - 2; minimum_los=1)
        end
    end
    return (direct_ward=direct_ward, post_icu_ward=post_icu_ward, icu=icu)
end

function _mss_profiles(spec_ids::Vector{Int}, n_days::Int)
    S = length(spec_ids)
    ward = zeros(Float64, S, n_days)
    icu = zeros(Float64, S, n_days)
    for s in 1:S
        components = _mss_profile_components(_ORSCHED_SPECIALTIES[spec_ids[s]], n_days)
        ward[s, :] .= components.direct_ward .+ components.post_icu_ward
        icu[s, :] .= components.icu
    end
    return ward, icu
end

function OperatingRoomMasterScheduleProblem(
    target_variables::Int, feasibility_status::FeasibilityStatus, seed::Int
)
    rng = MersenneTwister(seed)
    dims = _mss_dimensions(max(target_variables, 20))
    S, R, D = dims.s, dims.r, dims.d
    spec_ids = _orsched_case_mix(rng, S)

    compatible = falses(R, S)
    base_rooms = shuffle(rng, collect(1:R))
    for s in 1:S
        # Round-robin anchors ensure no room receives more than D specialty
        # guarantees, while the shuffled room order preserves seed diversity.
        compatible[base_rooms[mod1(s, R)], s] = true
    end
    remaining = [(r, s) for s in 1:S for r in 1:R if !compatible[r, s]]
    for (r, s) in shuffle(rng, remaining)[1:max(0, dims.pairs - S)]
        compatible[r, s] = true
    end

    max_daily = [rand(rng, 1:max(1, min(R, ceil(Int, 0.45R)))) for _ in 1:S]
    planted = zeros(Int, S, R, D)
    occupied = falses(R, D)
    # One guaranteed block per specialty.
    for s in 1:S
        r = base_rooms[mod1(s, R)]
        d = cld(s, R)
        @assert compatible[r, s] && !occupied[r, d]
        planted[s, r, d] = 1
        occupied[r, d] = true
    end
    # Fill a realistic 70--90% of remaining blocks while respecting daily
    # concentration.  These extra blocks create heterogeneous feasible quotas.
    fill_rate = rand(rng, Uniform(0.70, 0.90))
    for r in randperm(rng, R), d in randperm(rng, D)
        occupied[r, d] && continue
        rand(rng) <= fill_rate || continue
        choices = [s for s in 1:S if compatible[r, s] && sum(planted[s, :, d]) < max_daily[s]]
        isempty(choices) && continue
        weights = [_ORSCHED_SPECIALTIES[spec_ids[s]].weight for s in choices]
        s = choices[_orsched_pick(rng, cumsum(weights))]
        planted[s, r, d] = 1
        occupied[r, d] = true
    end

    counts = [sum(planted[s, :, :]) for s in 1:S]
    target_blocks = copy(counts)
    min_blocks = [max(1, counts[s] - rand(rng, 0:min(1, counts[s] - 1))) for s in 1:S]
    max_blocks = [counts[s] + rand(rng, 0:2) for s in 1:S]
    ward_profile, icu_profile = _mss_profiles(spec_ids, D)

    function occupancy(profile)
        return [
            sum(
                profile[s, mod(d - dp, D) + 1] * planted[s, r, dp] for s in 1:S, r in 1:R, dp in 1:D
            ) for d in 1:D
        ]
    end
    planted_ward = occupancy(ward_profile)
    planted_icu = occupancy(icu_profile)
    ward_capacity = ceil.(1.10 .* planted_ward .+ 1.0)
    icu_capacity = ceil.(1.15 .* planted_icu .+ 1.0)
    infeasible_specialty = nothing
    witness = feasibility_status == feasible ? planted : nothing

    if feasibility_status == infeasible
        victim = argmin([sum(compatible[:, s]) for s in 1:S])
        min_blocks[victim] = sum(compatible[:, victim]) * D + 1
        target_blocks[victim] = min_blocks[victim]
        max_blocks[victim] = min_blocks[victim] + 1
        ward_capacity .= 1.0e6
        icu_capacity .= 1.0e6
        infeasible_specialty = victim
    elseif feasibility_status == unknown
        # Natural scenario: quotas and capacities fluctuate around the planted
        # reference but no witness or hidden certificate is retained.
        for s in 1:S
            min_blocks[s] = max(1, target_blocks[s] + rand(rng, -1:1))
            max_blocks[s] = max(min_blocks[s], target_blocks[s] + rand(rng, 0:2))
        end
        ward_capacity .*= rand(rng, Uniform(0.90, 1.10))
        icu_capacity .*= rand(rng, Uniform(0.90, 1.10))
    end

    admissible = [(s, r, d) for d in 1:D for r in 1:R for s in 1:S if compatible[r, s]]
    preference = [rand(rng, Uniform(0.0, 50.0)) for _ in admissible]
    open_cost = [rand(rng, Uniform(300.0, 900.0)) for _ in 1:R, _ in 1:D]
    under = [rand(rng, Uniform(300.0, 700.0)) for _ in 1:S]
    over = [rand(rng, Uniform(100.0, 300.0)) for _ in 1:S]

    return OperatingRoomMasterScheduleProblem(
        S,
        R,
        D,
        [_ORSCHED_SPECIALTIES[k].name for k in spec_ids],
        target_blocks,
        min_blocks,
        max_blocks,
        max_daily,
        compatible,
        admissible,
        preference,
        open_cost,
        ward_profile,
        icu_profile,
        ward_capacity,
        icu_capacity,
        under,
        over,
        rand(rng, Uniform(10.0, 30.0)),
        rand(rng, Uniform(20.0, 50.0)),
        witness,
        infeasible_specialty,
        feasibility_status,
    )
end

function build_model(prob::OperatingRoomMasterScheduleProblem)
    model = Model()
    S, R, D = prob.n_specialties, prob.n_rooms, prob.n_days
    A = length(prob.admissible_blocks)
    @variable(model, assign_block[1:A], Bin)
    @variable(model, open_room[1:R, 1:D], Bin)
    @variable(model, under_blocks[1:S] >= 0)
    @variable(model, over_blocks[1:S] >= 0)
    @variable(model, ward_occupancy[1:D] >= 0)
    @variable(model, icu_occupancy[1:D] >= 0)
    @variable(model, peak_ward >= 0)
    @variable(model, peak_icu >= 0)

    by_room_day = Dict((r, d) => Int[] for r in 1:R for d in 1:D)
    by_specialty = [Int[] for _ in 1:S]
    by_specialty_day = Dict((s, d) => Int[] for s in 1:S for d in 1:D)
    for (a, (s, r, d)) in enumerate(prob.admissible_blocks)
        push!(by_room_day[(r, d)], a)
        push!(by_specialty[s], a)
        push!(by_specialty_day[(s, d)], a)
    end

    @constraint(
        model,
        room_exclusivity[r = 1:R, d = 1:D],
        sum(assign_block[a] for a in by_room_day[(r, d)]; init=0.0) == open_room[r, d]
    )
    for s in 1:S
        @constraint(
            model,
            sum(assign_block[a] for a in by_specialty[s]) + under_blocks[s] - over_blocks[s] ==
                prob.target_blocks[s]
        )
        @constraint(model, sum(assign_block[a] for a in by_specialty[s]) >= prob.min_blocks[s])
        @constraint(model, sum(assign_block[a] for a in by_specialty[s]) <= prob.max_blocks[s])
        for d in 1:D
            @constraint(
                model,
                sum(assign_block[a] for a in by_specialty_day[(s, d)]; init=0.0) <=
                    prob.max_daily_rooms[s]
            )
        end
    end

    for d in 1:D
        ward_terms = [
            (a, prob.ward_profile[s, mod(d - dp, D) + 1]) for
            (a, (s, _, dp)) in enumerate(prob.admissible_blocks)
        ]
        icu_terms = [
            (a, prob.icu_profile[s, mod(d - dp, D) + 1]) for
            (a, (s, _, dp)) in enumerate(prob.admissible_blocks)
        ]
        @constraint(
            model, ward_occupancy[d] == sum(coef * assign_block[a] for (a, coef) in ward_terms)
        )
        @constraint(
            model, icu_occupancy[d] == sum(coef * assign_block[a] for (a, coef) in icu_terms)
        )
        @constraint(model, ward_occupancy[d] <= prob.ward_capacity[d])
        @constraint(model, icu_occupancy[d] <= prob.icu_capacity[d])
        @constraint(model, peak_ward >= ward_occupancy[d])
        @constraint(model, peak_icu >= icu_occupancy[d])
    end

    @objective(
        model,
        Min,
        sum(prob.preference_cost[a] * assign_block[a] for a in 1:A) +
            sum(prob.room_open_cost[r, d] * open_room[r, d] for r in 1:R, d in 1:D) +
            sum(
                prob.under_penalty[s] * under_blocks[s] + prob.over_penalty[s] * over_blocks[s] for
                s in 1:S
            ) +
            prob.peak_ward_weight * peak_ward +
            prob.peak_icu_weight * peak_icu
    )
    return model
end

register_variant(
    :operating_room_scheduling,
    :master_surgical_schedule,
    OperatingRoomMasterScheduleProblem,
    "Sparse tactical cyclic master-surgical-schedule block allocation with room affinities, quotas, and separate ICU-to-ward occupancy leveling",
)
